### PR TITLE
Use importlib.metadata for version detection

### PR DESCRIPTION
**Pull request by zhiltsov-max**
### Summary

Our old mechanism for version declaration should become obsolete with py3.7 EOL. Currently, [the recommended way](https://docs.python.org/3/library/importlib.metadata.html#distribution-versions) is to use `importlib.metadata.version` function. This PR changes version declaration way to use this new function.

### Checklist

- [ ] I submit my changes into the `develop` branch
- [ ] I have added description of my changes into [CHANGELOG](https://github.com/cvat-ai/datumaro/blob/develop/CHANGELOG.md)
- [ ] I have updated the [documentation](https://github.com/cvat-ai/datumaro/tree/develop/docs) accordingly
- [ ] I have added tests to cover my changes
- [ ] I have [linked related issues](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword)

### License

- [ ] I submit _my code changes_ under the same [MIT License](
  https://github.com/cvat-ai/datumaro/blob/develop/LICENSE) that covers the project.
  Feel free to contact the maintainers if that's a concern.
- [ ] I have updated the license header for each file (see an example below)

```python
# Copyright (C) 2022 CVAT.ai Corporation
#
# SPDX-License-Identifier: MIT
```

### CODE REVIEW

**Comment by SpecLad** [comment]
I don't see any benefit from this. In fact, I can think of a couple drawbacks:

1. This new method will not work if Datumaro is used without being installed (e.g., via `datum.py`, or by being vendored into another source tree). It will even give the wrong answer if another copy of Datumaro is installed in the current environment.
2. It adds another dependency.

**Comment by zhiltsov-max** [comment]
The main benefits are that we have less code to maintain and we use a solution from the standard library. What is the problem with the extra dependency for py3.7?

**Comment by zhiltsov-max** [comment]
The main benefits are that we have less code to maintain and we use a solution from the standard library. What is the problem with the extra dependency for py3.7?

**Comment by SpecLad** [comment]
> The main benefits are that we have less code to maintain

You could also achieve that by setting the version in `setup.cfg` via the `attr:` directive.

> What is the problem with the extra dependency for py3.7?

The more dependencies there are, the higher chance that something'll break due to an unexpected update.

**Comment by zhiltsov-max** [comment]
> You could also achieve that by setting the version in setup.cfg via the attr: directive.

So the versions would be defined in 2 places? This is the same as `setup(..., version=..., ...)` without using `importlib.metadata`

**Comment by SpecLad** [comment]
> So the versions would be defined in 2 places?

Not really. It would say `version = attr: datumaro.version.VERSION`. The actual number would still only be in one place.

**Comment by SpecLad** [comment]
Also FWIW, this functionality of setuptools can also be accessed [via `pyproject.toml`](https://setuptools.pypa.io/en/latest/userguide/pyproject_config.html#dynamic-metadata), but that's currently in beta.

**Comment by zhiltsov-max** [comment]
Probably, a static `setup.cfg` (as well as [the poetry variant](https://github.com/cvat-ai/datumaro/blob/zm/move-to-poetry/pyproject.toml)) is not compatible with our logic in `setup.py` about opencv version.

**Comment by SpecLad** [comment]
There's no need to put _every_ setting in `setup.cfg`. It can coexist with `setup.py`.

**Pull request closed without merging**
